import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Revision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-amber-400 flex gap-4 p-4">
          <Link href="/about">About</Link>
          <Link href="/about">Contact</Link>
          <Link href="/about">Presentation</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
